Sync the CI action.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,5 @@
+on: [push, pull_request]
 name: Continuous Integration
-
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
 
 jobs:
   inspect-code:
@@ -14,7 +9,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      # FIXME: Tools won't run in .NET 6.0 unless you install 3.1.x LTS side by side.
+      # FIXME: Tools won't run in .NET 5.0 unless you install 3.1.x LTS side by side.
       # https://itnext.io/how-to-support-multiple-net-sdks-in-github-actions-workflows-b988daa884e
       - name: Install .NET 3.1.x LTS
         uses: actions/setup-dotnet@v1
@@ -30,34 +25,29 @@ jobs:
         run: dotnet tool restore
 
       - name: Restore Packages
-        run: dotnet restore
+        run: dotnet restore osu-framework-microphone.Desktop.slnf
 
       - name: Restore inspectcode cache
         uses: actions/cache@v3
         with:
           path: ${{ github.workspace }}/inspectcode
-          key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'osu-framework-microphone.sln*', '.editorconfig', '.globalconfig', 'CodeAnalysis/*') }}
+          key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'osu-framework-microphone.sln*', 'osu-framework-microphone*.slnf', '.editorconfig', '.globalconfig', 'CodeAnalysis/*') }}
 
       - name: Dotnet code style
-        run: dotnet build -c Debug -warnaserror build/Desktop.proj -p:EnforceCodeStyleInBuild=true
+        run: dotnet build -c Debug -warnaserror osu-framework-microphone.Desktop.slnf -p:EnforceCodeStyleInBuild=true
 
-      # todo: add this test back.
-      # - name: CodeFileSanity
-      #   run: |
-      #     # TODO: Add ignore filters and GitHub Workflow Command Reporting in CFS. That way we don't have to do this workaround.
-      #     # FIXME: Suppress warnings from templates project
-      #     exit_code=0
-      #     while read -r line; do
-      #       if [[ ! -z "$line" && "$line" != *"/osu.Framework.Templates/"* ]]; then
-      #         echo "::error::$line"
-      #         exit_code=1
-      #       fi
-      #     done <<< $(dotnet codefilesanity)
-      #     exit $exit_code
-
-      # Temporarily disabled due to test failures, but it won't work anyway until the tool is upgraded.
-      # - name: .NET Format (Dry Run)
-      #   run: dotnet format --dry-run --check
+      - name: CodeFileSanity
+        run: |
+          # TODO: Add ignore filters and GitHub Workflow Command Reporting in CFS. That way we don't have to do this workaround.
+          # FIXME: Suppress warnings from templates project
+          exit_code=0
+          while read -r line; do
+            if [[ ! -z "$line" && "$line" != *"/osu.Framework.Templates/"* ]]; then
+              echo "::error::$line"
+              exit_code=1
+            fi
+          done <<< $(dotnet codefilesanity)
+          exit $exit_code
 
       - name: InspectCode
         run: dotnet jb inspectcode $(pwd)/osu-framework-microphone.Desktop.slnf --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
@@ -70,15 +60,17 @@ jobs:
     runs-on: ${{matrix.os.fullname}}
     env:
       OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
+      OSU_TESTS_LOCAL_HTTPBIN: 1
     strategy:
-       fail-fast: false
-       matrix:
-          os:
-            - { prettyname: Windows, fullname: windows-latest }
-            - { prettyname: macOS, fullname: macos-latest }
-            - { prettyname: Linux, fullname: ubuntu-latest }
-          threadingMode: ['SingleThread', 'MultiThreaded']
+      fail-fast: false
+      matrix:
+        os:
+          - { prettyname: Windows, fullname: windows-latest }
+          - { prettyname: macOS, fullname: macos-latest }
+          - { prettyname: Linux, fullname: ubuntu-latest }
+        threadingMode: ['SingleThread', 'MultiThreaded']
     timeout-minutes: 60
+
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -88,20 +80,21 @@ jobs:
         with:
           dotnet-version: "6.0.x"
 
-      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
-      # https://github.com/ppy/osu-framework/issues/4349
-      # Remove this once https://github.com/actions/virtual-environments/issues/3306 has been resolved.
-      - name: Install libavformat-dev
-        if: ${{matrix.os.fullname == 'ubuntu-latest'}}
-        run: |
-         sudo apt-get update && \
-         sudo apt-get -y install libavformat-dev
+      - name: Setup Go
+        uses: actions/setup-go@v3
+
+      - name: Install httpbin
+        run: go install github.com/mccutchen/go-httpbin/v2/cmd/go-httpbin@latest
+
+      - name: Run httpbin
+        run: $HOME/go/bin/go-httpbin &
+        shell: bash
 
       - name: Compile
-        run: dotnet build -c Debug -warnaserror build/Desktop.proj
+        run: dotnet build -c Debug -warnaserror osu-framework-microphone.Desktop.slnf
 
       - name: Test
-        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --settings $pwd/build/vstestconfig.runsettings --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"
+        run: dotnet test $pwd/**/*.Tests/bin/Debug/*/*.Tests.dll --settings $pwd/build/vstestconfig.runsettings --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"
         shell: pwsh
 
       # Attempt to upload results even if test fails.
@@ -126,11 +119,11 @@ jobs:
         with:
           dotnet-version: "6.0.x"
 
-      - name: Setup MSBuild
-        uses: microsoft/setup-msbuild@v1
+      - name: Restore .NET workloads
+        run: dotnet workload restore
 
-      - name: Build
-        run: msbuild osu-framework-microphone.Android.slnf /restore /p:Configuration=Debug
+      - name: Compile
+        run: dotnet build -c Debug osu-framework-microphone.Android.slnf
 
   build-only-ios:
     name: Build only (iOS)
@@ -145,8 +138,8 @@ jobs:
         with:
           dotnet-version: "6.0.x"
 
-      # Contrary to seemingly any other msbuild, msbuild running on macOS/Mono
-      # cannot accept .sln(f) files as arguments.
-      # Build just the iOS framework project for now.
-      - name: Build
-        run: msbuild osu.Framework.Microphone.iOS/osu.Framework.Microphone.iOS.csproj /restore /p:Configuration=Debug
+      - name: Restore .NET workloads
+        run: dotnet workload restore
+
+      - name: Compile
+        run: dotnet build -c Debug osu-framework-microphone.iOS.slnf
